language: android
jdk: oraclejdk8
cache: false
sudo: true
android:
  components:
  - build-tools-26.0.2
  - android-26
  - android-25
  - android-24
  - extra-android-m2repository
  - extra-android-support
script:
- "./gradlew assembleRelease"
before_script:
- mkdir -p "$ANDROID_HOME/licenses"
- cp ./android-sdk-license "$ANDROID_HOME/licenses/"
- cp ./hiddenapi/26/android.jar "$ANDROID_HOME/platforms/android-26/"
- cp ./hiddenapi/25/android.jar "$ANDROID_HOME/platforms/android-25/"
after_script:
- sudo apt-get install tree
- tree app/
notifications:
  email:
    recipients:
    - tornaco@163.com
    on_success: always
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_9386c2da478c_key -iv $encrypted_9386c2da478c_iv
  -in keys_android.jks.enc -out keys/keys_android.jks -d
deploy:
  provider: releases
  api_key:
    secure: X+GW206d6MM62TgdzKjsg0MAHlG3ePNtKRxtY5sW/zXrjEcoT5RGwA+j2GissO2uhFKkFPemUzR2HJQ2GbA00dQghF13r/7Pyhi1Ufwb7KXqaGNq7danFA9naC+zZuTpFuz+2iTkfn28JAC+ciRHmSFePcX95HiTxbXd+KN0DTsnsKcdyuNKirADcGGaG+oVIrtG2opSDG0vIiwXsgvL88c+VtYj6Yy6Bz/FRQrzxqv281bnTjThDn1s4e323z4qC7qOMd+lih7GnpAxi2AcR4El86gorO2qMmvWVfnH4fx9T9IsJ+AluD/0H9BxjfBEpj9AW04d9wF/OrXfic5yQ4iyd3se1fmRrxtPraz4XuaU3zP6ZIst/Sw0qTVkRwPF5cP58eiYXn+QOpuQ3xcTJAA0I5vRZrK4UAWcQFFsHJ2STJM/t2VgAgnlmnYk3RPh94/GyXQOSxlvBLdpMuJcJ029U4Xr+BjW0XeN0jqpmcWrzHi8Lok0GnEj2zKm1d51CtHvw5w88uyaNAUFualR4vrCImJ9GdYW3zBD+4w2ssSxqyQAkr4nW6ZJScnU108UGZYtA9Qe8+H95L1zVfSLnGfHv4uTkQP4jF7v6u8FZPeWDvfcLQi+FJqOalkXr3vA2Shc1LvScAuzokhzsfxuJGgsBy6pfIfprDmapWjyu5Y=
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    repo: Tornaco/XAppGuard
    tags: true
    all_branches: true
